### PR TITLE
some css stuff

### PR DESCRIPTION
**Pull request by dmartss**

### CODE REVIEW

**Comment by hewhowearspants** [comment]
Looks ok, did Carly see this? Just wanna make sure she's not doing CSS changes too that might clash with this.

**Comment by dmartss** [comment]
not sure ill slack our group, but I was on a train out of the city last night and was only able to do css on the train

**Comment by dmartss** [comment]
"looks ok" thanks lol

**Comment by hewhowearspants** [comment]
'looks ok', y'know, like 'I don't know what it looks like yet but that code sure looks tidy!'

**Comment by dmartss** [comment]
LGTM!!

**Pull request merged**
